### ISSUE TITLE
Cache built-in tasks

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/azure-devops-marketplace#12]
This repository contains the data for Azure Pipelines tasks from the marketplace, but the built-in tasks data is still contained in the main Renovate repository. The built-in task data should also be generated here.

- https://github.com/renovatebot/renovate/blob/main/tools/static-data/generate-azure-pipelines-tasks.mjs
- https://github.com/renovatebot/renovate/blob/main/data/azure-pipelines-tasks.json

**Comment by viceice** [comment]
can you open a PR to it to this repo?

**Comment by jessehouwing** [comment]
@viceice @JamieMagee That turned out even simpler than I expected. Pull request opened. I'll be out of office the upcoming days.

**Comment by jessehouwing** [comment]
This is in the end why it's probably better to finish the work to read directly from the Azure DevOps Organization of the user, instead of trying to build a cache file:

https://github.com/renovatebot/renovate/issues/19725

**Comment by viceice** [comment]
yes, but until someone finished that we should move the cache file here and out of renovate repo.

**Comment by jessehouwing** [comment]
Bluiltin tasks are now also updated.

**Comment by viceice** [comment]
so next step is to fetch the new file on the fly from renovate datasource like we do for the marketplace.
