### ISSUE TITLE
Incorrect PublishCodeCoverageResults version data

### ISSUE THREAD

**Issue by bdovaz** [renovatebot/azure-devops-marketplace#42]
The `PublishCodeCoverageResults` task is starting to fail and there seems to be an inconsistency.

1. The version in the repository for this task points to `2.242.0`:

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PublishCodeCoverageResultsV2/task.json

2. If I run this url with my organization it returns `2.240.1` so I understand that although in the repository it is `2.242.0` it is not published yet or it was but it has been removed:

https://dev.azure.com/{MY_ORG}/_apis/distributedtask/tasks?allversions=true

3. In the file generated with the workflow of this repository points to `2.242.1`:

https://github.com/renovatebot/azure-devops-marketplace/blob/main/azure-pipelines-builtin-tasks.json

The latter causes that when I create the PR updating to that version I get this failure because that version does not exist:

`A task is missing. The pipeline references a task called 'PublishCodeCoverageResults'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 2.242.1, job '', step ''.) 20240720.1`

**Comment by jessehouwing** [comment]
Not all Azure DevOps deployment rings update at the same time. The Renovate Azure devIps instance we poll is quite early in the deployment order. If you want to ensure the task exists on *your* instance of Azure DevOps, either put configure a wait timer in Renovate or check for the presence of the specific task in your environment.

There is an issue open on the main renovate repo to rewrite this mechanism to actually check *your* Azure DevOps instance, but that hasn't progressed beyond the design stage unfortunately.

**Comment by bdovaz** [comment]
@jessehouwing what is the issue out of curiosity? Thank you.

**Comment by jessehouwing** [comment]
https://github.com/renovatebot/renovate/discussions/24820
